name: Merge Conflicts

on:
  push:
    branches:
      - master

jobs:
  validate:

    name: Check for merge conflicts
    runs-on: ubuntu-latest

    steps:
      - uses: mschilde/auto-label-merge-conflicts@master
        with:
          CONFLICT_LABEL_NAME: 'Merge conflicts'
          GITHUB_TOKEN: "${{ secrets.GITHUB_TOKEN }}"
